# Generated by Django 4.0.1 on 2022-01-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter author first name', max_length=100, verbose_name='Author first name')),
                ('last_name', models.CharField(help_text='Enter author last name', max_length=100, verbose_name='Author last name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter a author`s date of birth', null=True, verbose_name='Author date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter a author`s date of death', null=True, verbose_name='Author date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a book name', max_length=200, verbose_name='Book name')),
                ('summary', models.TextField(help_text='Enter description of this book', max_length=1000, verbose_name='Book summary')),
                ('isbn', models.CharField(help_text='Must be 13 symbols in length', max_length=13)),
                ('author', models.ManyToManyField(help_text='Enter author', null=True, to='catalog.Author', verbose_name='Book author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=200, verbose_name='Book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book language', max_length=20, verbose_name='Book language')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book status', max_length=20, verbose_name='Book status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivn_nom', models.CharField(help_text='Enter the inventory number of the book', max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Enter publisher and year of release', max_length=200, null=True, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Enter status expiration date', null=True, verbose_name='Expiration date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Edit a book status', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Book status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Enter a book genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Book genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Enter a book language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Book language'),
        ),
    ]
