# Generated by Django 4.0.1 on 2022-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Enter author', to='catalog.Author', verbose_name='Book author'),
        ),
    ]
