# Generated by Django 4.0.1 on 2022-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity books in order', verbose_name='quantity'),
        ),
    ]
